import numpy as np
from spline import calculate_position_and_directions


def write_apdl_commands(filepath: str,
                        points: np.ndarray,
                        goldak_parameters: np.ndarray,
                        welding_duration: int,
                        cooling_duration: int, ):
    total_length, speed, positions, directions = calculate_position_and_directions(points, welding_duration)

    file = open(filepath, "w")

    file.write(f"! --------------------------------------------\n")
    file.write(f"! 1) Define Goldak Heat Source Parameters\n")
    file.write(f"! --------------------------------------------\n")
    file.write(f"\n")
    file.write(f"*set,c,{goldak_parameters[1]}\n")
    file.write(f"*set,b,{goldak_parameters[2]}\n")
    file.write(f"*set,af,{goldak_parameters[3]}\n")
    file.write(f"*set,ar,{goldak_parameters[4]}\n")
    file.write(f"*set,ff,{goldak_parameters[5]}\n")
    file.write(f"*set,fr,{goldak_parameters[6]}\n")
    file.write(f"*set,qval,{goldak_parameters[0]}\n")
    file.write(f"*set,pi,3.141592654\n")
    file.write(f"\n")
    file.write(f"! --------------------------------------------\n")
    file.write(f"! 2) Perform the Welding Simulation\n")
    file.write(f"! --------------------------------------------\n")
    file.write(f"\n")
    file.write(f"*get,maxelem,elem,0,num,max\n")
    file.write(f"\n")
    file.write(f"cm_sel='surfaces'\n")
    file.write(f"cmsel,s,cm_sel\n")
    file.write(f"sfe,all,conv,,{goldak_parameters[7]},{goldak_parameters[8]}\n")
    file.write(f"allsel,all\n")
    file.write(f"\n")

    for t in range(welding_duration):
        file.write(f"wtime={t + 1}\n")
        file.write(f"time,wtime\n")
        file.write(f"\n")
        file.write(f"bfe,all,hgen,0,0\n")
        file.write(f"\n")
        file.write(f"x0={positions[t][0]}\n")
        file.write(f"y0={positions[t][1]}\n")
        file.write(f"z0={positions[t][2]}\n")
        file.write(f"\n")
        file.write(f"ux={directions[t][0]}\n")
        file.write(f"uy={directions[t][1]}\n")
        file.write(f"uz={directions[t][2]}\n")
        file.write(f"\n")
        file.write(f"unorm = SQRT(ux**2 + uy**2 + uz**2)\n")
        file.write(f"ux = ux/unorm\n")
        file.write(f"uy = uy/unorm\n")
        file.write(f"uz = uz/unorm\n")
        file.write(f"\n")
        file.write(f"*IF, ABS(ux), LE, 0.9, THEN\n")
        file.write(f"\trx = 1\n")
        file.write(f"\try = 0\n")
        file.write(f"\trz = 0\n")
        file.write(f"\n")
        file.write(f"*ELSE\n")
        file.write(f"\trx = 0\n")
        file.write(f"\try = 1\n")
        file.write(f"\trz = 0\n")
        file.write(f"*ENDIF\n")
        file.write(f"\n")
        file.write(f"vx = uy*rz - uz*ry\n")
        file.write(f"vy = uz*rx - ux*rz\n")
        file.write(f"vz = ux*ry - uy*rx\n")
        file.write(f"vnorm = SQRT(vx**2 + vy**2 + vz**2)\n")
        file.write(f"vx = vx/vnorm\n")
        file.write(f"vy = vy/vnorm\n")
        file.write(f"vz = vz/vnorm\n")
        file.write(f"\n")
        file.write(f"wx = uy*vz - uz*vy\n")
        file.write(f"wy = uz*vx - ux*vz\n")
        file.write(f"wz = ux*vy - uy*vx\n")
        file.write(f"\n")
        file.write(f"*do,eid,1,maxelem,1\n")
        file.write(f"\t*GET,ex,elem,eid,CENT,X\n")
        file.write(f"\t*GET,ey,elem,eid,CENT,Y\n")
        file.write(f"\t*GET,ez,elem,eid,CENT,Z\n")
        file.write(f"\n")
        file.write(f"\tdx = ex - x0\n")
        file.write(f"\tdy = ey - y0\n")
        file.write(f"\tdz = ez - z0\n")
        file.write(f"\n")
        file.write(f"\tparx = ux*dx + uy*dy + uz*dz\n")
        file.write(f"\tpary = vx*dx + vy*dy + vz*dz\n")
        file.write(f"\tparz = wx*dx + wy*dy + wz*dz\n")
        file.write(f"\n")
        file.write(f"\t*IF,parx,GE,0,THEN\n")
        file.write(f"\t\ta = af\n")
        file.write(f"\t\tf = ff\n")
        file.write(f"\t*ELSE\n")
        file.write(f"\t\ta = ar\n")
        file.write(f"\t\tf = fr\n")
        file.write(f"\t*ENDIF\n")
        file.write(f"\n")
        file.write(f"\tk = 6*SQRT(3)*f*qval / (pi*SQRT(pi)*a*b*c)\n")
        file.write(f"\ttempExp = -3*((parx/a)**2 + (pary/b)**2 + (parz/c)**2)\n")
        file.write(f"\tq_effect = k*EXP(tempExp)\n")
        file.write(f"\tbfe,eid,HGEN,,q_effect\n")
        file.write(f"\n")
        file.write(f"*enddo\n")
        file.write(f"\n")
        file.write(f"solve\n")
        file.write(f"\n")

    file.write(f"! --------------------------------------------\n")
    file.write(f"! 3) Perform the Cooling Simulation\n")
    file.write(f"! --------------------------------------------\n")
    file.write(f"\n")

    for td in range(cooling_duration):
        td = td + 1 + welding_duration
        file.write(f"wtime={td}\n")
        file.write(f"time,wtime\n")
        file.write(f"\n")
        file.write(f"bfe,all,hgen,0,0\n")
        file.write(f"\n")
        file.write(f"solve\n")
        file.write(f"\n")

    file.close()
